// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/time/v1/time.proto

package timev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowRequest) Reset() {
	*x = NowRequest{}
	mi := &file_proto_time_v1_time_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowRequest) ProtoMessage() {}

func (x *NowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_time_v1_time_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowRequest.ProtoReflect.Descriptor instead.
func (*NowRequest) Descriptor() ([]byte, []int) {
	return file_proto_time_v1_time_proto_rawDescGZIP(), []int{0}
}

type NowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unix          int64                  `protobuf:"varint,1,opt,name=unix,proto3" json:"unix,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowResponse) Reset() {
	*x = NowResponse{}
	mi := &file_proto_time_v1_time_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowResponse) ProtoMessage() {}

func (x *NowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_time_v1_time_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowResponse.ProtoReflect.Descriptor instead.
func (*NowResponse) Descriptor() ([]byte, []int) {
	return file_proto_time_v1_time_proto_rawDescGZIP(), []int{1}
}

func (x *NowResponse) GetUnix() int64 {
	if x != nil {
		return x.Unix
	}
	return 0
}

func (x *NowResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_proto_time_v1_time_proto protoreflect.FileDescriptor

const file_proto_time_v1_time_proto_rawDesc = "" +
	"\n" +
	"\x18proto/time/v1/time.proto\x12\atime.v1\"\f\n" +
	"\n" +
	"NowRequest\";\n" +
	"\vNowResponse\x12\x12\n" +
	"\x04unix\x18\x01 \x01(\x03R\x04unix\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice2?\n" +
	"\vTimeService\x120\n" +
	"\x03Now\x12\x13.time.v1.NowRequest\x1a\x14.time.v1.NowResponseB2Z0github.com/imoudgil/servkit/proto/time/v1;timev1b\x06proto3"

var (
	file_proto_time_v1_time_proto_rawDescOnce sync.Once
	file_proto_time_v1_time_proto_rawDescData []byte
)

func file_proto_time_v1_time_proto_rawDescGZIP() []byte {
	file_proto_time_v1_time_proto_rawDescOnce.Do(func() {
		file_proto_time_v1_time_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_time_v1_time_proto_rawDesc), len(file_proto_time_v1_time_proto_rawDesc)))
	})
	return file_proto_time_v1_time_proto_rawDescData
}

var file_proto_time_v1_time_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_time_v1_time_proto_goTypes = []any{
	(*NowRequest)(nil),  // 0: time.v1.NowRequest
	(*NowResponse)(nil), // 1: time.v1.NowResponse
}
var file_proto_time_v1_time_proto_depIdxs = []int32{
	0, // 0: time.v1.TimeService.Now:input_type -> time.v1.NowRequest
	1, // 1: time.v1.TimeService.Now:output_type -> time.v1.NowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_time_v1_time_proto_init() }
func file_proto_time_v1_time_proto_init() {
	if File_proto_time_v1_time_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_time_v1_time_proto_rawDesc), len(file_proto_time_v1_time_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_time_v1_time_proto_goTypes,
		DependencyIndexes: file_proto_time_v1_time_proto_depIdxs,
		MessageInfos:      file_proto_time_v1_time_proto_msgTypes,
	}.Build()
	File_proto_time_v1_time_proto = out.File
	file_proto_time_v1_time_proto_goTypes = nil
	file_proto_time_v1_time_proto_depIdxs = nil
}
